spring.application.name=Athenix-Back

# Server
server.servlet.context-path=/api/v1

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/athenix?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
spring.datasource.username=root
spring.datasource.password=hugerich77
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# JWT
jwt.secret=aHR0cHM6Ly9hdGhlbml4LWJhY2suY29tL2p3dC9zZWNyZXQta2V5LXlvdXItc3VwZXItc3RyaWN0LWxvbmctand0LXNlY3JldC1rZXktZm9yLWhzNTEyLWFsZ29yaXRobS1yZmM3NTE4
jwt.expiration=3600000
jwt.refresh-expiration=604800000

# File Upload
app.storage.path=/tmp/athenix-uploads
app.storage.max-file-size=1073741824

# Multipart Upload Size
spring.servlet.multipart.max-file-size=1GB
spring.servlet.multipart.max-request-size=1GB

# Logging
logging.level.root=INFO
logging.level.com.community.athenixback=INFO

# AI Server
# ?: ai.server.url=http://192.168.1.100:8000
ai.server.url=http://10.129.49.198:8000
ai.server.endpoint.recommend=/ai/recommend/image
